(() => {
  'use strict';
  const cfg = window.SMART_VOICE_CONFIG || {apiBase:''};
  const base = String(cfg.apiBase || '').replace(/\/$/, '');
  const $ = (s, p=document) => p.querySelector(s);
  const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const icon = (name) => name==='mic' ? '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="9" y="3" width="6" height="12" rx="3"/><path d="M5 11a7 7 0 0 0 14 0M12 18v3m-4 0h8"/></svg>' : name==='send' ? '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/></svg>' : '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 3a9 9 0 1 0 9 9"/><path d="M12 7v5l3 2"/><path d="M17 2v5h5"/></svg>';
  const shell = document.createElement('div');
  shell.innerHTML = `<button id="sv-launch" aria-label="Открыть разговор с ИИ" title="Разговор с ИИ">${icon('mic')}</button>
  <section id="sv-panel" aria-label="Голосовой ИИ-помощник" aria-hidden="true"><header class="sv-head"><div class="sv-orb">✦</div><div class="sv-head-main"><b>Музыкальный собеседник</b><span class="sv-status"><i class="sv-dot"></i><span id="sv-status">Готов общаться</span></span></div><button class="sv-x" id="sv-close" aria-label="Закрыть">×</button></header><div class="sv-messages" id="sv-messages" aria-live="polite"><div class="sv-empty"><div class="sv-big">✧</div><b>О чём поболтаем?</b><p>Спроси что угодно, расскажи о настроении или попроси помочь с музыкой. Ответы создаёт ИИ.</p></div></div><div class="sv-suggestions"><button data-prompt="Привет! Давай познакомимся">Познакомиться</button><button data-prompt="Посоветуй музыку под моё настроение">Музыка под настроение</button><button data-prompt="Расскажи что-нибудь интересное">Удиви меня</button></div><footer class="sv-compose"><div class="sv-inputrow"><textarea id="sv-text" class="sv-text" rows="1" maxlength="2000" placeholder="Напиши или нажми на микрофон…"></textarea><button id="sv-mic" class="sv-iconbtn" aria-label="Записать голос">${icon('mic')}</button><button id="sv-send" class="sv-iconbtn sv-send" aria-label="Отправить">${icon('send')}</button></div><div class="sv-footnote">Голос сгенерирован ИИ · Не произноси пароли и личные данные</div><button class="sv-stop" id="sv-stop" hidden>Остановить голос</button></footer></section>`;
  document.body.appendChild(shell);
  const panel=$('#sv-panel'), messages=$('#sv-messages'), input=$('#sv-text'), send=$('#sv-send'), mic=$('#sv-mic'), status=$('#sv-status'), stopBtn=$('#sv-stop');
  let history=[], busy=false, recorder=null, stream=null, chunks=[], currentSpeech=null, currentSpeechUrl=null, currentAudio=null, priorVolume=null;
  const setStatus = s => status.textContent=s;
  const open = () => {panel.classList.add('sv-open');panel.setAttribute('aria-hidden','false');setTimeout(()=>input.focus({preventScroll:true}),100)};
  const close = () => {panel.classList.remove('sv-open');panel.setAttribute('aria-hidden','true'); stopRecording();};
  $('#sv-launch').addEventListener('click',()=>panel.classList.contains('sv-open')?close():open()); $('#sv-close').addEventListener('click',close);
  function addMsg(role,text,extra=''){ const empty=$('.sv-empty',messages); if(empty)empty.remove(); const el=document.createElement('div');el.className='sv-msg '+role+(extra?' '+extra:'');el.textContent=text;messages.appendChild(el);messages.scrollTop=messages.scrollHeight;return el; }
  function typing(){const el=document.createElement('div');el.className='sv-msg assistant';el.innerHTML='<span class="sv-typing"><i></i><i></i><i></i></span>';messages.appendChild(el);messages.scrollTop=messages.scrollHeight;return el;}
  async function request(path, options={}) { if(!base)throw new Error('Сначала укажи HTTPS-адрес backend в smart-voice-config.js. Инструкция есть в README.'); const r=await fetch(base+path,{...options,headers:{...(options.headers||{}),...(options.body instanceof FormData?{}:{'Content-Type':'application/json'})}}); if(!r.ok){let msg='Ошибка сервера ('+r.status+')';try{const j=await r.json();if(j.error)msg=j.error}catch{}throw new Error(msg)} return r; }
  function stopSpeech(){ if(currentAudio){currentAudio.pause();currentAudio.src='';currentAudio=null} if(currentSpeechUrl){URL.revokeObjectURL(currentSpeechUrl);currentSpeechUrl=null} stopBtn.hidden=true; }
  async function speak(text){ stopSpeech(); try{setStatus('Готовлю голос…');const r=await request('/api/speech',{method:'POST',body:JSON.stringify({text})});const blob=await r.blob();currentSpeechUrl=URL.createObjectURL(blob);currentAudio=new Audio(currentSpeechUrl);currentAudio.preload='auto';currentAudio.onended=()=>{stopSpeech();setStatus('Готов общаться')};currentAudio.onerror=()=>{stopSpeech();setStatus('Готов общаться')};stopBtn.hidden=false;await currentAudio.play();setStatus('Отвечаю голосом');}catch(e){setStatus('Ответ готов · голос недоступен');console.warn('TTS:',e.message)} }
  stopBtn.addEventListener('click',stopSpeech);
  async function sendMessage(text){text=String(text||'').trim();if(!text||busy)return;open();addMsg('user',text);input.value='';input.style.height='auto';history.push({role:'user',content:text});history=history.slice(-12);busy=true;send.disabled=true;mic.disabled=true;setStatus('Думаю…');const wait=typing();try{const r=await request('/api/chat',{method:'POST',body:JSON.stringify({messages:history})});const data=await r.json();wait.remove();const answer=String(data.reply||'Не получилось сформировать ответ.').slice(0,5000);addMsg('assistant',answer);history.push({role:'assistant',content:answer});history=history.slice(-12);await speak(answer);}catch(e){wait.remove();addMsg('assistant',e.message,'error');setStatus('Не удалось подключиться')}finally{busy=false;send.disabled=false;mic.disabled=false;input.focus({preventScroll:true})}}
  send.addEventListener('click',()=>sendMessage(input.value));input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage(input.value)}});input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,100)+'px'});
  document.querySelectorAll('.sv-suggestions button').forEach(b=>b.addEventListener('click',()=>sendMessage(b.dataset.prompt)));
  async function startRecording(){ if(busy)return; if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){addMsg('assistant','Этот браузер не поддерживает запись голоса. Напиши сообщение текстом.','error');return} try{stopSpeech();stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});chunks=[];let type='';for(const t of ['audio/webm;codecs=opus','audio/webm','audio/mp4','audio/ogg;codecs=opus'])if(MediaRecorder.isTypeSupported(t)){type=t;break}recorder=new MediaRecorder(stream,type?{mimeType:type}:undefined);recorder.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data)};recorder.onstop=async()=>{const blob=new Blob(chunks,{type:recorder?.mimeType||'audio/webm'});cleanupMic();if(blob.size<1000){setStatus('Не удалось записать речь');return}await transcribe(blob)};recorder.start();mic.classList.add('recording');mic.setAttribute('aria-label','Остановить запись');mic.innerHTML='■';setStatus('Слушаю… нажми ■, когда закончишь');}catch(e){cleanupMic();setStatus('Нет доступа к микрофону');addMsg('assistant','Разреши доступ к микрофону в настройках браузера и проверь, что сайт открыт по HTTPS.','error')}}
  function cleanupMic(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}recorder=null;mic.classList.remove('recording');mic.innerHTML=icon('mic');mic.setAttribute('aria-label','Записать голос')}
  function stopRecording(){if(recorder&&recorder.state!=='inactive'){recorder.stop()}else cleanupMic()}
  async function transcribe(blob){setStatus('Распознаю речь…');mic.disabled=true;try{const fd=new FormData();const ext=blob.type.includes('mp4')?'m4a':blob.type.includes('ogg')?'ogg':'webm';fd.append('audio',blob,'voice.'+ext);const r=await request('/api/transcribe',{method:'POST',body:fd});const data=await r.json();const text=String(data.text||'').trim();if(text){setStatus('Речь распознана');await sendMessage(text)}else setStatus('Не расслышал — попробуй ещё раз')}catch(e){addMsg('assistant',e.message,'error');setStatus('Ошибка распознавания')}finally{mic.disabled=false}}
  mic.addEventListener('click',()=>{if(recorder&&recorder.state!=='inactive')stopRecording();else startRecording()});
  window.addEventListener('pagehide',()=>{stopSpeech();stopRecording()});
})();
