import 'dotenv/config';
import express from 'express';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import multer from 'multer';
import OpenAI from 'openai';

const app=express();
const port=Number(process.env.PORT||3000);
const apiKey=process.env.OPENAI_API_KEY;
const openai=apiKey?new OpenAI({apiKey,timeout:60000,maxRetries:1}):null;
app.disable('x-powered-by'); app.set('trust proxy', Number(process.env.TRUST_PROXY||0));
app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}}));
app.use(express.json({limit:'24kb'}));
const allowedOrigin=(process.env.ALLOWED_ORIGIN||'').trim();
app.use((req,res,next)=>{const origin=req.headers.origin;if(origin&&(!allowedOrigin||origin!==allowedOrigin))return res.status(403).json({error:'Этот сайт не разрешён для подключения к помощнику. Проверь ALLOWED_ORIGIN на backend.'});if(origin){res.setHeader('Access-Control-Allow-Origin',allowedOrigin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');}if(req.method==='OPTIONS')return res.sendStatus(204);next()});
const limiter=rateLimit({windowMs:60_000,limit:20,standardHeaders:'draft-7',legacyHeaders:false,message:{error:'Слишком много запросов. Подожди минуту и попробуй снова.'}});
app.use('/api/',limiter);
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:12*1024*1024,files:1},fileFilter:(req,file,cb)=>{const ok=/^audio\/(webm|mp4|ogg|mpeg|wav|x-wav|aac|mp4a-latm|3gpp|flac)/i.test(file.mimetype)||/\.(webm|m4a|ogg|mp3|wav|aac|3gp)$/i.test(file.originalname);cb(ok?null:new Error('Неподдерживаемый аудиоформат.'),ok)}});
app.get('/health',(req,res)=>res.json({ok:true,configured:Boolean(openai)}));
function needAI(res){if(!openai){res.status(503).json({error:'Backend ещё не настроен: добавь OPENAI_API_KEY в переменные окружения сервера.'});return false}return true}
app.post('/api/chat',async(req,res)=>{if(!needAI(res))return;const raw=req.body?.messages;if(!Array.isArray(raw)||!raw.length||raw.length>12)return res.status(400).json({error:'Передай от 1 до 12 сообщений.'});const messages=[];let total=0;for(const m of raw){if(!m||!['user','assistant'].includes(m.role)||typeof m.content!=='string')continue;const content=m.content.trim().slice(0,2000);if(!content)continue;total+=content.length;messages.push({role:m.role,content})}if(!messages.length||messages[messages.length-1].role!=='user')return res.status(400).json({error:'Последнее сообщение должно быть от пользователя.'});if(total>8000)return res.status(413).json({error:'Слишком длинная переписка. Начни новый разговор.'});try{const response=await openai.responses.create({model:process.env.OPENAI_CHAT_MODEL||'gpt-5-mini',instructions:'Ты — дружелюбный разговорный ИИ-помощник внутри музыкального плеера. Отвечай на русском, естественно, тепло и по делу; можно лёгкий юмор, но без грубости и без притворства, что ты человек. Ты можешь беседовать на разные темы и помогать с музыкой. Важно: ты не управляешь плеером напрямую, если в сообщении нет доступного инструмента; не утверждай, что переключил трек, изменил громкость или видишь библиотеку. Если просят действие плеера, объясни коротко, что пока можно управлять кнопками. Обычно 1–4 коротких предложения, если не просят подробностей. Не проси пароли, адреса, платёжные данные и другие секреты.',input:messages.map(m=>({role:m.role,content:m.content})),max_output_tokens:350});const reply=String(response.output_text||'Я тут. Повтори, пожалуйста, чуть по-другому.').trim().slice(0,5000);res.json({reply})}catch(err){console.error('chat API error:',err?.status||err?.name||'error');res.status(502).json({error:err?.status===401?'API-ключ не принят. Проверь переменную OPENAI_API_KEY.':err?.status===429?'У API закончился доступный лимит или слишком много запросов. Проверь настройки биллинга и лимиты.':'ИИ временно недоступен. Попробуй ещё раз через несколько секунд.'})}});
app.post('/api/speech',async(req,res)=>{if(!needAI(res))return;const text=typeof req.body?.text==='string'?req.body.text.trim().slice(0,3500):'';if(!text)return res.status(400).json({error:'Нет текста для озвучивания.'});try{const speech=await openai.audio.speech.create({model:process.env.OPENAI_TTS_MODEL||'gpt-4o-mini-tts',voice:process.env.OPENAI_TTS_VOICE||'coral',input:text,instructions:'Speak in natural conversational Russian. Warm, relaxed, friendly voice, clear pronunciation, medium pace, like a helpful companion. Do not sound overly theatrical.',response_format:'mp3'});const buf=Buffer.from(await speech.arrayBuffer());res.set({'Content-Type':'audio/mpeg','Content-Length':String(buf.length),'Cache-Control':'no-store','X-AI-Generated-Audio':'true'});res.send(buf)}catch(err){console.error('speech API error:',err?.status||err?.name||'error');res.status(502).json({error:'Не удалось создать голосовой ответ.'})}});
app.post('/api/transcribe',upload.single('audio'),async(req,res)=>{if(!needAI(res))return;if(!req.file)return res.status(400).json({error:'Запись не получена.'});try{const file=new File([req.file.buffer],req.file.originalname||'voice.webm',{type:req.file.mimetype||'audio/webm'});const out=await openai.audio.transcriptions.create({model:process.env.OPENAI_TRANSCRIBE_MODEL||'gpt-4o-mini-transcribe',file,language:'ru',prompt:'Русская разговорная речь. Музыка, плеер, песни и повседневная беседа.'});res.json({text:String(out.text||'').slice(0,2000)})}catch(err){console.error('transcription API error:',err?.status||err?.name||'error');res.status(502).json({error:'Не удалось распознать голос. Попробуй ещё раз или напиши текстом.'})}});
app.use((err,req,res,next)=>{if(err instanceof multer.MulterError)return res.status(413).json({error:'Аудиозапись слишком большая (максимум 12 МБ).'});if(err) return res.status(400).json({error:err.message||'Некорректный запрос.'});next()});
app.listen(port,'0.0.0.0',()=>console.log(`Smart Voice backend listening on ${port}`));
